import type { ShelfLifeRule } from "@/lib/types";

/**
 * 食品保存规则库
 *
 * 每条规则包含：
 * - keyword: 匹配食品名称的关键词
 * - category: 食品分类
 * - recommendedStorageLocation: 建议存放位置
 * - shelfLifeByStorage: 按存放位置的参考保存天数
 * - openedAdjustment: 开封后的保存天数缩减比例 (0-1, 1 表示不缩减)
 * - referenceNote: 备注
 *
 * 注意：这些是初始参考规则，不能宣称为食品安全结论。
 * 实际可食用性请结合包装标识、保存条件及食品状态判断。
 */

export const shelfLifeRules: ShelfLifeRule[] = [
  // === 肉类 ===
  {
    keyword: "猪肉",
    category: "meat",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 3, freezer: 180 },
    openedAdjustment: 0.67,
    referenceNote: "冷藏短期保存，冷冻可长期保存",
  },
  {
    keyword: "牛肉",
    category: "meat",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 3, freezer: 240 },
    openedAdjustment: 0.67,
    referenceNote: "冷冻牛肉保存时间较长",
  },
  {
    keyword: "鸡肉",
    category: "meat",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 2, freezer: 180 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "排骨",
    category: "meat",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 3, freezer: 180 },
    openedAdjustment: 0.67,
  },
  {
    keyword: "羊肉",
    category: "meat",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 3, freezer: 180 },
    openedAdjustment: 0.67,
  },
  {
    keyword: "五花肉",
    category: "meat",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 3, freezer: 180 },
    openedAdjustment: 0.67,
  },
  {
    keyword: "鸡腿",
    category: "meat",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 2, freezer: 180 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "鸡翅",
    category: "meat",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 2, freezer: 180 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "培根",
    category: "meat",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 7, freezer: 60 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "香肠",
    category: "meat",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 14, freezer: 60 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "火腿",
    category: "meat",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 14, freezer: 60 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "腊肉",
    category: "meat",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 60, freezer: 180 },
    openedAdjustment: 0.67,
  },

  // === 水产 ===
  {
    keyword: "鱼",
    category: "seafood",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 2, freezer: 120 },
    openedAdjustment: 0.5,
    referenceNote: "新鲜鱼类应尽快食用",
  },
  {
    keyword: "虾",
    category: "seafood",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 2, freezer: 120 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "蟹",
    category: "seafood",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 1, freezer: 90 },
    openedAdjustment: 1,
  },
  {
    keyword: "贝",
    category: "seafood",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 1, freezer: 90 },
    openedAdjustment: 1,
  },
  {
    keyword: "鱿鱼",
    category: "seafood",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 2, freezer: 120 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "三文鱼",
    category: "seafood",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 2, freezer: 90 },
    openedAdjustment: 0.5,
  },

  // === 蛋奶 ===
  {
    keyword: "牛奶",
    category: "dairy",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 14, room: 1 },
    openedAdjustment: 0.36,
    referenceNote: "开封后请尽快饮用",
  },
  {
    keyword: "酸奶",
    category: "dairy",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 21 },
    openedAdjustment: 0.33,
  },
  {
    keyword: "鸡蛋",
    category: "egg",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 30, room: 14 },
    openedAdjustment: 0.1,
    referenceNote: "开封指蛋壳破损",
  },
  {
    keyword: "鸭蛋",
    category: "egg",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 30, room: 14 },
    openedAdjustment: 0.1,
  },
  {
    keyword: "鹌鹑蛋",
    category: "egg",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 21, room: 10 },
    openedAdjustment: 0.1,
  },
  {
    keyword: "奶酪",
    category: "dairy",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 30 },
    openedAdjustment: 0.33,
  },
  {
    keyword: "芝士",
    category: "dairy",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 30 },
    openedAdjustment: 0.33,
  },
  {
    keyword: "黄油",
    category: "dairy",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 90, freezer: 365 },
    openedAdjustment: 0.5,
  },

  // === 蔬菜 ===
  {
    keyword: "青菜",
    category: "vegetable",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 5, freezer: 60 },
    openedAdjustment: 0.6,
  },
  {
    keyword: "白菜",
    category: "vegetable",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 14, freezer: 60 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "菠菜",
    category: "vegetable",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 5, freezer: 60 },
    openedAdjustment: 0.6,
  },
  {
    keyword: "生菜",
    category: "vegetable",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 5, freezer: 30 },
    openedAdjustment: 0.6,
  },
  {
    keyword: "芹菜",
    category: "vegetable",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 7, freezer: 60 },
    openedAdjustment: 0.6,
  },
  {
    keyword: "韭菜",
    category: "vegetable",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 4 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "西红柿",
    category: "vegetable",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 7, room: 5 },
    openedAdjustment: 0.3,
  },
  {
    keyword: "番茄",
    category: "vegetable",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 7, room: 5 },
    openedAdjustment: 0.3,
  },
  {
    keyword: "黄瓜",
    category: "vegetable",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 7 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "胡萝卜",
    category: "vegetable",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 14, freezer: 60 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "土豆",
    category: "vegetable",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 30, fridge: 21 },
    openedAdjustment: 0.5,
    referenceNote: "阴凉干燥处保存",
  },
  {
    keyword: "洋葱",
    category: "vegetable",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 30, fridge: 21 },
    openedAdjustment: 0.3,
  },
  {
    keyword: "萝卜",
    category: "vegetable",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 14, freezer: 60 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "茄子",
    category: "vegetable",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 5 },
    openedAdjustment: 0.6,
  },
  {
    keyword: "辣椒",
    category: "vegetable",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 10, freezer: 60 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "青椒",
    category: "vegetable",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 10 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "蘑菇",
    category: "vegetable",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 5 },
    openedAdjustment: 0.6,
  },
  {
    keyword: "香菇",
    category: "vegetable",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 7, room: 30 },
    openedAdjustment: 0.5,
    referenceNote: "干香菇可常温保存",
  },
  {
    keyword: "葱",
    category: "vegetable",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 10, room: 5 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "姜",
    category: "vegetable",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 30, fridge: 21, freezer: 90 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "蒜",
    category: "vegetable",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 60, fridge: 30 },
    openedAdjustment: 0.3,
  },

  // === 水果 ===
  {
    keyword: "苹果",
    category: "fruit",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 21, room: 10 },
    openedAdjustment: 0.3,
  },
  {
    keyword: "香蕉",
    category: "fruit",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 5, fridge: 3 },
    openedAdjustment: 1,
    referenceNote: "不建议冷藏，易变黑",
  },
  {
    keyword: "葡萄",
    category: "fruit",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 7 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "草莓",
    category: "fruit",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 3 },
    openedAdjustment: 0.5,
    referenceNote: "易腐坏，尽快食用",
  },
  {
    keyword: "橙子",
    category: "fruit",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 21, room: 10 },
    openedAdjustment: 0.3,
  },
  {
    keyword: "橘子",
    category: "fruit",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 14, room: 7 },
    openedAdjustment: 0.3,
  },
  {
    keyword: "西瓜",
    category: "fruit",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 7, room: 3 },
    openedAdjustment: 0.3,
    referenceNote: "切开后必须冷藏",
  },
  {
    keyword: "蓝莓",
    category: "fruit",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 7, freezer: 180 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "芒果",
    category: "fruit",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 7, room: 5 },
    openedAdjustment: 0.3,
  },
  {
    keyword: "桃",
    category: "fruit",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 5, room: 3 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "梨",
    category: "fruit",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 14, room: 7 },
    openedAdjustment: 0.3,
  },
  {
    keyword: "柚子",
    category: "fruit",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 30, fridge: 21 },
    openedAdjustment: 0.3,
  },
  {
    keyword: "猕猴桃",
    category: "fruit",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 14, room: 7 },
    openedAdjustment: 0.3,
  },

  // === 主食 ===
  {
    keyword: "面包",
    category: "grain",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 5, fridge: 7, freezer: 30 },
    openedAdjustment: 0.6,
  },
  {
    keyword: "馒头",
    category: "grain",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 3, fridge: 5, freezer: 30 },
    openedAdjustment: 0.7,
  },
  {
    keyword: "面条",
    category: "grain",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 3, room: 1, freezer: 30 },
    openedAdjustment: 0.7,
    referenceNote: "鲜面条需冷藏",
  },
  {
    keyword: "饺子",
    category: "grain",
    recommendedStorageLocation: "freezer",
    shelfLifeByStorage: { freezer: 60, fridge: 2 },
    openedAdjustment: 0.7,
  },
  {
    keyword: "馄饨",
    category: "grain",
    recommendedStorageLocation: "freezer",
    shelfLifeByStorage: { freezer: 60, fridge: 2 },
    openedAdjustment: 0.7,
  },
  {
    keyword: "米",
    category: "grain",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 365 },
    openedAdjustment: 0.7,
    referenceNote: "干燥密封保存",
  },
  {
    keyword: "面粉",
    category: "grain",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 180, fridge: 365 },
    openedAdjustment: 0.7,
  },

  // === 调味品 ===
  {
    keyword: "酱油",
    category: "condiment",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 365 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "醋",
    category: "condiment",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 365 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "料酒",
    category: "condiment",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 365 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "蚝油",
    category: "condiment",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 180, room: 90 },
    openedAdjustment: 0.5,
    referenceNote: "开封后建议冷藏",
  },
  {
    keyword: "番茄酱",
    category: "condiment",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 180, room: 90 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "辣椒酱",
    category: "condiment",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 365 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "老干妈",
    category: "condiment",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 365 },
    openedAdjustment: 0.67,
  },
  {
    keyword: "盐",
    category: "condiment",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 1825 },
    openedAdjustment: 1,
  },
  {
    keyword: "糖",
    category: "condiment",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 730 },
    openedAdjustment: 1,
  },

  // === 饮料 ===
  {
    keyword: "可乐",
    category: "beverage",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 180, room: 180 },
    openedAdjustment: 0.04,
    referenceNote: "开封后当天饮用",
  },
  {
    keyword: "果汁",
    category: "beverage",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 10, room: 3 },
    openedAdjustment: 0.3,
  },
  {
    keyword: "啤酒",
    category: "beverage",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 180, room: 120 },
    openedAdjustment: 0.04,
  },
  {
    keyword: "矿泉水",
    category: "beverage",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 365 },
    openedAdjustment: 0.1,
  },
  {
    keyword: "茶",
    category: "beverage",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 365 },
    openedAdjustment: 0.5,
    referenceNote: "指瓶装茶饮；散装茶叶另有标准",
  },
  {
    keyword: "咖啡",
    category: "beverage",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 365 },
    openedAdjustment: 0.5,
  },

  // === 冷冻食品 ===
  {
    keyword: "冰淇淋",
    category: "frozen",
    recommendedStorageLocation: "freezer",
    shelfLifeByStorage: { freezer: 180 },
    openedAdjustment: 0.33,
  },
  {
    keyword: "雪糕",
    category: "frozen",
    recommendedStorageLocation: "freezer",
    shelfLifeByStorage: { freezer: 180 },
    openedAdjustment: 0.33,
  },
  {
    keyword: "速冻",
    category: "frozen",
    recommendedStorageLocation: "freezer",
    shelfLifeByStorage: { freezer: 180 },
    openedAdjustment: 0.5,
  },

  // === 熟食/剩菜 ===
  {
    keyword: "熟食",
    category: "leftover",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 3 },
    openedAdjustment: 1,
  },
  {
    keyword: "剩菜",
    category: "leftover",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 2 },
    openedAdjustment: 1,
    referenceNote: "建议尽快食用",
  },
  {
    keyword: "剩饭",
    category: "leftover",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 2, freezer: 30 },
    openedAdjustment: 1,
  },
  {
    keyword: "打包",
    category: "leftover",
    recommendedStorageLocation: "fridge",
    shelfLifeByStorage: { fridge: 2 },
    openedAdjustment: 1,
  },

  // === 零食 ===
  {
    keyword: "零食",
    category: "snack",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 180 },
    openedAdjustment: 0.33,
  },
  {
    keyword: "饼干",
    category: "snack",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 180 },
    openedAdjustment: 0.33,
  },
  {
    keyword: "薯片",
    category: "snack",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 90 },
    openedAdjustment: 0.1,
    referenceNote: "开封后尽快食用",
  },
  {
    keyword: "巧克力",
    category: "snack",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 365, fridge: 365 },
    openedAdjustment: 0.5,
  },
  {
    keyword: "坚果",
    category: "snack",
    recommendedStorageLocation: "room",
    shelfLifeByStorage: { room: 180 },
    openedAdjustment: 0.33,
  },
];

/** 默认保质期（无法匹配任何规则时的兜底值） */
export const DEFAULT_SHELF_LIFE: Record<string, number> = {
  fridge: 7,
  freezer: 90,
  room: 30,
};
